#! /bin/bash

for  alpha1 in $(seq 6 0.1 9); do 
    bin/vad --alpha1 $alpha1 -i pav_231.wav -o pav_231.vad
    echo -en "$alpha1\t"
    scripts/vad_evaluation.pl pav_231.lab | grep "===>"
done | sort -t: -k2n
