#! /bin/bash

for  alpha1 in $(seq 6 0.1 8); do
    for dif in $(seq 0 0.1 1); do
    alpha2=$(echo "$alpha1 - $dif" | bc)
    echo -en "$alpha1\t$alpha2\t"
    scripts/run_vad.sh $alpha1 $alpha2 | grep "TOTAL"
    done
done | sort -t: -k2n
